# This configuration is prod-ready, and you SHOULD NOT edit it.
# If you want to override and customize the configuration, mount a "config.local.yml" to your container!

version: "1.0.0"

http:
  listen: "0.0.0.0"
  port: 8000

rateLimiter:
  limit: "1000-H"
  prefix: "limiter_skmcparser"

redis:
  address: "185.157.247.16:6379"
  username: ""
  password : "WQVNpQrBgKcndRvyk"
  db: 0
